# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullname', models.CharField(max_length=50)),
                ('account_created_on', models.DateTimeField(auto_now_add=True)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
    ]
