# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_uploaded_on', models.DateTimeField(auto_created=True)),
                ('doc_title', models.CharField(max_length=50)),
                ('doc_type', models.CharField(max_length=10)),
                ('doc_tags', models.CharField(default='', max_length=50)),
                ('doc_description', models.CharField(default='', max_length=100)),
                ('doc_path', models.FileField(upload_to='/documents')),
                ('doc_uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users')),
            ],
        ),
    ]
