# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_path',
            field=models.FileField(upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_uploaded_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
