# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20160403_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_path',
            field=models.FileField(upload_to=''),
        ),
    ]
