# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_stats_statsadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatsAdmin',
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_tags',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
