# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20160411_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_image',
            field=models.FileField(default='./book_icon_grey.png', upload_to=''),
        ),
    ]
